### ISSUE TITLE
Can translate only from English

### ISSUE THREAD

**Issue by anufry** [ankitpopli1891/django-autotranslate#22] opened 2019-10-27 21:52 UTC
In autotranslate/management/commands/translate_messages.py : 96 hardcoded 'en' as source_language.

Better set to settings.LANGUAGE_CODE or add own setting var for this app

**Comment by diogosimao** [comment] 2020-02-26 11:59
What about using commands like this:

> $ python manage.py translate_messages -l 'de' -l 'es'

It's still fixed on '_en_'?

**Comment by ankitpopli1891** [comment] 2020-04-16 10:30
Yep. Closing this as a dupe of #18 

I've not had a chance to work on it again!

I'm not sure when I'm gonna be able to work on it again!

**Closed as completed by ankitpopli1891** 2020-04-16 10:30 UTC
